export const categoryProducts = [
  {
    title: "Футболки",
    imgMen: "/categorymen/1.webp",
    categorySlug: "futbolki",
    gender: ["men"],
  },
  {
    title: "Шорти",
    imgMen: "/categorymen/2.webp",
    className: "scale-110 hover:scale-120",
    categorySlug: "shortu",
    gender: ["men"],
  },
  {
    title: "Спортивні костюми",
    imgMen: "/categorymen/3.webp",
    imgWomen:"/categorywomen/1.webp",
    categorySlug: "tracksuit",
    className: "scale-110 hover:scale-120",
    gender: ["men", "women"],
  },
  {
    title: "Кофти/Худі",
    imgMen: "/categorymen/4.webp",
    imgWomen:"/categorywomen/2.webp",
    categorySlug: "hudi-sweter",
    className: "scale-110 hover:scale-120",
    gender: ["men", "women"],
  },
  {
    title: "Штани",
    imgMen: "/categorymen/5.webp",
    className: "scale-110 hover:scale-120",
    imgWomen:"/categorywomen/3.webp",
    categorySlug: "shtanu",
    gender: ["men", "women"],
  },
  {
    title: "Вітровки",
    imgMen: "/categorymen/6.webp",
    imgWomen:"/categorywomen/4.webp",
    className: "scale-110 hover:scale-120",
    categorySlug: "vitrovki",
    gender: ["men", "women"],
  },
  {
    title: "Жилети",
    imgMen: "/categorymen/7.webp",
    imgWomen:"/categorywomen/5.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "zhilety",
    gender: ["men", "women"],
  },
  {
    title: "Термобілизна",
    imgMen: "/categorymen/8.webp",
    imgWomen:"/categorywomen/6.webp",
    className: "scale-110 hover:scale-120",
    categorySlug: "termobilizna",
    gender: ["men", "women"],
  },
  {
    title: "Куртки",
    imgMen: "/categorymen/9.webp",
    imgWomen:"/categorywomen/7.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "kurtky",
    gender: ["men", "women"],
  },
  {
    title: "Лижні куртки",
    imgMen: "/categorymen/10.webp",
    imgWomen:"/categorywomen/8.webp",
    className: "scale-120  hover:scale-130",
    categorySlug: "lizhnye-kurtki",
    gender: ["men", "women"],
  },
  //отсюда
  {
    title: "Легінси",
    imgWomen: "/categorywomen/9.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "legincu",
    gender:  ["women"],
  },
  {
    title: "Топи",
    imgWomen: "/categorywomen/10.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "topu",
    gender:  ["women"],
  },
  {
    title: "Фітнес одяг",
    imgWomen: "/categorywomen/11.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "fitnec-odiag",
    gender:  ["women"],
  },
  
  {
    title: "Лижні штани",
    imgWomen: "/categorywomen/12.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "lizhnye-wtanu",
    gender:  ["women"],
  },
  {
    title: "Кепки",
    imgAccessories: "/categorywomen/12.webp",
    className: "scale-110  hover:scale-120",
    categorySlug: "kepki",
    gender:  ["accessories"],
  },
  
];
