import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Footer, Header, InfoHeader } from "@/shared/components";
import Providers from "@/shared/components/providers";
import { ModalCart } from "@/shared/components/modal-cart";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Avecs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${montserrat.variable} font-sans`}
      >
        <Providers>
          <InfoHeader />
          <Header />
          <ModalCart />
          <div className="flex-1">{children}</div>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
