import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import { Header, InfoHeader, ModalAddToCart } from "@/shared/components";
import Providers from "@/shared/components/providers";
import { ModalCart } from "@/shared/components/modal-cart";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { notFound } from "next/navigation";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Avecs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${montserrat.variable} font-sans`}
      >
        <Providers>
          <InfoHeader />
          <Header />
          <ModalCart />

          <ModalAddToCart />
          {children}
        </Providers>
      </body>
    </html>
  );
}
